apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'com.omooo.lavender'
//invokeCheckConfig {
//    methodList = [
//            "android.widget.Toast#makeText",
//            "android.widget.Toast",
//            "android.widget.Toast#show()V",
//    ]
//    packageList = [
//            "com.omooo.library",
//    ]
//}

//checkSchemeModifiedConfig {
//    enable = true
//    baselineSchemeFile = file("runtime/devRelease/runtimeSchemes.json")
//}

apply plugin: 'com.spotify.ruler'
ruler {
    abi.set("arm64-v8a")
    locale.set("zh")
    screenDensity.set(480)
    sdkVersion.set(33)
}

android {
    compileSdkVersion 34
    namespace 'com.omooo.plugin'
    defaultConfig {
        applicationId "com.omooo.plugin"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation(project(":library"))
}

kotlin {
    jvmToolchain(17)
}
